#!/usr/bin/python

from mips32 import 



#!/usr/bin/python

import sys

def main():
    for line in sys.stdin:
        print line

# parse out operator
# parse out operands

    return 0

if __name__ == '__main__':
    sys.exit(main())

